# Heading

> Quote

`dd` to delete a cell. `b` to insert a cell below. `a` to insert a cell above. `z` to undo, `x` to cut, `v` to paste and `c` to copy.

`Escape` key to enter command mode. `Enter` to go into edit mode on active cell. User arrow keys to navigate up and down

When in command mode, hit `m` to change type of active cell to markdown and `y` to change type to code

`Ctrl + Enter` runs code and stays in same cell. `Shift + Enter` runs code and goes to next cell.

# Numpy

In [7]:
import numpy as np
import sys

a = np.array([42,34,21,65,75])
b = np.array([42,34,21,65,75], dtype=float)

In [10]:
a.dtype, a, b.dtype, b

(dtype('int64'),
 array([42, 34, 21, 65, 75]),
 dtype('float64'),
 array([42., 34., 21., 65., 75.]))

### Multi-indexing

In [12]:
a[[0,2,4]], a[0], a[2], a[4]

(array([42, 21, 75]), 42, 21, 75)

### Dimensions and shapes

In [20]:
# r X c
A = np.array(
[
    [23,54,45],
    [12,343,65]
]
) # dimensions must match

In [16]:
A.size

6

In [19]:
A.shape

(2, 3)

In [23]:
A[1:, 1:] # A[r,c]

array([[343,  65]])

In [28]:
A[1] = np.array([10,10,20])

In [30]:
A

array([[23, 54, 45],
       [10, 10, 20]])

In [31]:
A[0] = 11 # expands by itself

In [33]:
A

array([[11, 11, 11],
       [10, 10, 20]])

### Summary stats

In [35]:
A.sum(), A.mean(),A.std(),A.var()

(73, 12.166666666666666, 3.531603350069515, 12.472222222222223)

In [38]:
A.sum(axis=0) # adds rows, keeps columns

array([21, 21, 31])

In [40]:
A.sum(axis = 1) # adds columns, keeps rows

array([33, 40])

### Broadcasting and vectorized operations

In [41]:
x = np.arange(4)

In [42]:
x

array([0, 1, 2, 3])

In [55]:
x + 10 # returns new array

array([70, 71, 72, 73])

In [56]:
x * 10 # returns new array

array([600, 610, 620, 630])

In [57]:
x += 10 # modifies existing array

In [54]:
x

array([60, 61, 62, 63])

In [59]:
y = np.array([5,5,5,5])

In [60]:
x+y,x*y

(array([75, 76, 77, 78]), array([350, 355, 360, 365]))

### Boolean Arrays

In [62]:
x[[0, -1]] # returns first and last element 

array([70, 73])

In [63]:
x[[True, False, False, True]] # does the same thing

array([70, 73])

In [65]:
a 

array([42, 34, 21, 65, 75])

In [66]:
a >= 35

array([ True, False, False,  True,  True])

In [69]:
a[a >= 35]

array([42, 65, 75])

In [70]:
a[a > a.mean()]

array([65, 75])

In [73]:
a[~(a > a.mean())] # not operation

array([42, 34, 21])

In [76]:
a[(a == 34) | (a == 65)] # OR operation

array([34, 65])

In [77]:
a[(a < a.mean()) & (a % 2 == 0)] # AND operation

array([42, 34])

In [80]:
z = np.random.randint(100, size=(3,3))

In [81]:
z

array([[12, 79, 46],
       [ 9, 29, 44],
       [84, 91, 76]])

In [82]:
z[z > 50]

array([79, 84, 91, 76])

### Linear Algebra

In [86]:
M = np.array([
    [1,2],
    [3,4]
])

N = np.array([
    [5,6],
    [7,8]
])

In [87]:
M.dot(N)

array([[19, 22],
       [43, 50]])

In [88]:
M @ N

array([[19, 22],
       [43, 50]])

In [89]:
M.T # Transpose

array([[1, 3],
       [2, 4]])

# Size of objects in memory

In [93]:
sys.getsizeof(1) # python number size

28

In [94]:
np.dtype(int).itemsize # numpy relative has very smaller size

8

In [95]:
pyList = list(range(1000))
npArray = np.arange(1000)

In [96]:
%time np.sum(a ** 2)

CPU times: user 231 µs, sys: 88 µs, total: 319 µs
Wall time: 324 µs


13211

In [97]:
%time sum([x ** 2 for x in pyList])

CPU times: user 377 µs, sys: 0 ns, total: 377 µs
Wall time: 386 µs


332833500