# Heading

> Quote

`dd` to delete a cell. `b` to insert a cell below. `a` to insert a cell above. `z` to undo, `x` to cut, `v` to paste and `c` to copy.

`Escape` key to enter command mode. `Enter` to go into edit mode on active cell. User arrow keys to navigate up and down

When in command mode, hit `m` to change type of active cell to markdown and `y` to change type to code

`Ctrl + Enter` runs code and stays in same cell. `Shift + Enter` runs code and goes to next cell.

# Numpy

In [7]:
import numpy as np
import sys

a = np.array([42,34,21,65,75])
b = np.array([42,34,21,65,75], dtype=float)

In [10]:
a.dtype, a, b.dtype, b

(dtype('int64'),
 array([42, 34, 21, 65, 75]),
 dtype('float64'),
 array([42., 34., 21., 65., 75.]))

### Multi-indexing

In [12]:
a[[0,2,4]], a[0], a[2], a[4]

(array([42, 21, 75]), 42, 21, 75)

### Dimensions and shapes

In [20]:
# r X c
A = np.array(
[
    [23,54,45],
    [12,343,65]
]
) # dimensions must match

In [16]:
A.size

6

In [19]:
A.shape

(2, 3)

In [23]:
A[1:, 1:] # A[r,c]

array([[343,  65]])

In [28]:
A[1] = np.array([10,10,20])

In [30]:
A

array([[23, 54, 45],
       [10, 10, 20]])

In [31]:
A[0] = 11 # expands by itself

In [33]:
A

array([[11, 11, 11],
       [10, 10, 20]])

### Summary stats

In [35]:
A.sum(), A.mean(),A.std(),A.var()

(73, 12.166666666666666, 3.531603350069515, 12.472222222222223)

In [38]:
A.sum(axis=0) # adds rows, keeps columns

array([21, 21, 31])

In [40]:
A.sum(axis = 1) # adds columns, keeps rows

array([33, 40])

### Broadcasting and vectorized operations

In [41]:
x = np.arange(4)

In [42]:
x

array([0, 1, 2, 3])

In [55]:
x + 10 # returns new array

array([70, 71, 72, 73])

In [56]:
x * 10 # returns new array

array([600, 610, 620, 630])

In [57]:
x += 10 # modifies existing array

In [54]:
x

array([60, 61, 62, 63])

In [59]:
y = np.array([5,5,5,5])

In [60]:
x+y,x*y

(array([75, 76, 77, 78]), array([350, 355, 360, 365]))

### Boolean Arrays

In [62]:
x[[0, -1]] # returns first and last element 

array([70, 73])

In [63]:
x[[True, False, False, True]] # does the same thing

array([70, 73])

In [65]:
a 

array([42, 34, 21, 65, 75])

In [66]:
a >= 35

array([ True, False, False,  True,  True])

In [69]:
a[a >= 35]

array([42, 65, 75])

In [70]:
a[a > a.mean()]

array([65, 75])

In [73]:
a[~(a > a.mean())] # not operation

array([42, 34, 21])

In [76]:
a[(a == 34) | (a == 65)] # OR operation

array([34, 65])

In [77]:
a[(a < a.mean()) & (a % 2 == 0)] # AND operation

array([42, 34])

In [80]:
z = np.random.randint(100, size=(3,3))

In [81]:
z

array([[12, 79, 46],
       [ 9, 29, 44],
       [84, 91, 76]])

In [82]:
z[z > 50]

array([79, 84, 91, 76])

### Linear Algebra

In [86]:
M = np.array([
    [1,2],
    [3,4]
])

N = np.array([
    [5,6],
    [7,8]
])

In [87]:
M.dot(N)

array([[19, 22],
       [43, 50]])

In [88]:
M @ N

array([[19, 22],
       [43, 50]])

In [89]:
M.T # Transpose

array([[1, 3],
       [2, 4]])

# Size of objects in memory

In [93]:
sys.getsizeof(1) # python number size

28

In [94]:
np.dtype(int).itemsize # numpy relative has very smaller size

8

In [95]:
pyList = list(range(1000))
npArray = np.arange(1000)

In [96]:
%time np.sum(a ** 2)

CPU times: user 231 µs, sys: 88 µs, total: 319 µs
Wall time: 324 µs


13211

In [97]:
%time sum([x ** 2 for x in pyList])

CPU times: user 377 µs, sys: 0 ns, total: 377 µs
Wall time: 386 µs


332833500

# Pandas

In [3]:
import pandas as pd
import numpy as np

pop = pd.Series([23.3,43.5,234.3,87.3])
pop.name = 'population'
pop

0     23.3
1     43.5
2    234.3
3     87.3
Name: population, dtype: float64

In [12]:
pop.index

RangeIndex(start=0, stop=4, step=1)

In [14]:
pop.index = ['India','US','Canada','Italy']

In [15]:
pop

India      23.3
US         43.5
Canada    234.3
Italy      87.3
Name: population, dtype: float64

In [17]:
pop['US']

43.5

In [19]:
pop.iloc[-1]

87.3

In [21]:
pop.iloc[[1,2]] # upper limit is included unlike python a[low:upper]

US         43.5
Canada    234.3
Name: population, dtype: float64

In [22]:
pop[['India','US']]

India    23.3
US       43.5
Name: population, dtype: float64

In [23]:
pop > 50

India     False
US        False
Canada     True
Italy      True
Name: population, dtype: bool

In [24]:
pop[pop>50]

Canada    234.3
Italy      87.3
Name: population, dtype: float64

In [25]:
pop + 100

India     123.3
US        143.5
Canada    334.3
Italy     187.3
Name: population, dtype: float64

In [1]:
pop[pop < 100] = 4444
pop

NameError: name 'pop' is not defined

## Dataframe

In [5]:
# a lot like table
df = pd.DataFrame({
    'num_legs': [2, 4, 8, 0],
    'num_wings': [2, 0, 0, 0],
    'num_specimen_seen': [10, 2, 1, 8]},
    index=['falcon', 'dog', 'spider', 'fish'])
df

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

In [7]:
# select by rows/index
df.loc['dog']

num_legs             4
num_wings            0
num_specimen_seen    2
Name: dog, dtype: int64

In [9]:
# select by rows/index but only some columns
df.loc['dog',['num_wings','num_legs']]

num_wings    0
num_legs     4
Name: dog, dtype: int64

In [11]:
df.loc['dog':'spider','num_wings'] # upper limit is included

dog       0
spider    0
Name: num_wings, dtype: int64

In [15]:
# select rows by index

df.iloc[1:3,1:2] # upper limit not included

num_wings
dog             0
spider          0

In [19]:
# select by columns
df['num_specimen_seen']


falcon    10
dog        2
spider     1
fish       8
Name: num_specimen_seen, dtype: int64

In [21]:
df.columns

Index(['num_legs', 'num_wings', 'num_specimen_seen'], dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, falcon to fish
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   num_legs           4 non-null      int64
 1   num_wings          4 non-null      int64
 2   num_specimen_seen  4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes


In [26]:
df.describe()

num_legs  num_wings  num_specimen_seen
count   4.00000        4.0           4.000000
mean    3.50000        0.5           5.250000
std     3.41565        1.0           4.425306
min     0.00000        0.0           1.000000
25%     1.50000        0.0           1.750000
50%     3.00000        0.0           5.000000
75%     5.00000        0.5           8.500000
max     8.00000        2.0          10.000000

In [36]:
df.loc[(df['num_legs'] > 3) & (df['num_specimen_seen'] % 2 == 0)]

num_legs  num_wings  num_specimen_seen
dog         4          0                  2

In [41]:
df.drop('fish')

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1

In [43]:
df

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

In [44]:
df.drop(columns='num_wings')

num_legs  num_specimen_seen
falcon         2                 10
dog            4                  2
spider         8                  1
fish           0                  8

In [57]:
# broadcasting operation

df.loc['dog':'fish',['num_legs','num_wings']] + 100

num_legs  num_wings
dog          104        100
spider       108        100
fish         100        100

In [55]:
df.loc[(df['num_legs'] > 3) & (df['num_specimen_seen'] % 2 == 0)] + 100

num_legs  num_wings  num_specimen_seen
dog       104        100                102

In [72]:
# add new column

eyes = pd.Series([2,2,2],name = 'num_eyes',index=['dog','fish','falcon'])
eyes

dog       2
fish      2
falcon    2
Name: num_eyes, dtype: int64

In [73]:
df['num_eyes'] =  eyes

In [74]:
df

num_legs  num_wings  num_specimen_seen  num_eyes
falcon         2          2                 10       2.0
dog            4          0                  2       2.0
spider         8          0                  1       NaN
fish           0          0                  8       2.0

In [83]:
df.rename(index=str.upper)

num_legs  num_wings  num_specimen_seen  num_eyes
FALCON         2          2                 10       2.0
DOG            4          0                  2       2.0
SPIDER         8          0                  1       NaN
FISH           0          0                  8       2.0